-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        border_size = 1,
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@75.00Hz",
    position = "24960x0",
    scale = 1,
    cm = "srgb",
})
