-- Generated by HyprMod

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@75.00Hz",
    position = "17280x0",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.01Hz",
    position = "15360x0",
    scale = 1,
    cm = "srgb",
})
